apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/gateway
    repoURL: https://github.com/bernardolsp/microservicos-argocd-treinamento
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true