apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - warehouse.yaml
  - analysistemplates/           # AnalysisTemplates para verification
  - stages/dev.yaml
  - stages/staging.yaml
  - stages/prod.yaml
  - applications/dev.yaml
  - applications/staging.yaml
  - applications/prod.yaml