kind: ClusterSecretStore
apiVersion: external-secrets.io/v1
metadata:
  name: aws-sm
  namespace: external-secrets-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1