apiVersion: generators.external-secrets.io/v1alpha1
kind: ECRAuthorizationToken
metadata:
  name: ecr
  namespace: argocd
spec:
  region: us-east-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ecr-oci
  namespace: argocd
spec:
  refreshInterval: 30m
  target: 
    name: ecr-oci
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        name: ecr-oci
        type: helm
        enableOCI: "true"
        url: 628042573059.dkr.ecr.us-east-1.amazonaws.com
        password: "{{ .password }}"
        username: "{{ .username }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ECRAuthorizationToken
          name: ecr