apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secondary-eks-lab
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  target:
    name: secondary-eks-lab
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
  data:
    - secretKey: config
      remoteRef:
        key: argocd-cluster-secret-secondary-lab
        property: config
    - secretKey: name
      remoteRef:
        key: argocd-cluster-secret-secondary-lab
        property: name
    - secretKey: server
      remoteRef:
        key: argocd-cluster-secret-secondary-lab
        property: server