---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: argocd-training
  region: us-east-1
  version: "1.34"
  tags:
    Environment: training
    Project: argocd-intensive
    ManagedBy: eksctl
    karpenter.sh/discovery: argocd-training

# IAM Identity Mappings - Allow Karpenter nodes to join
iamIdentityMappings:
  - arn: arn:aws:iam::628042573059:role/KarpenterNodeRole-argocd-training
    username: system:node:{{EC2PrivateDNSName}}
    groups:
      - system:bootstrappers
      - system:nodes

# VPC Configuration - Creates a new VPC with 3 AZs
vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Single  # making this less expensive lol

# Availability Zones - Explicitly define 3 AZs for HA
availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

# IAM Configuration
iam:
  withOIDC: true  # Enable OIDC provider for IRSA (IAM Roles for Service Accounts)
  serviceAccounts:
    # Service Account for Karpenter Controller
    - metadata:
        name: karpenter
        namespace: kube-system
      roleName: KarpenterController-argocd-training
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:CreateFleet
              - ec2:CreateLaunchTemplate
              - ec2:CreateTags
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceTypeOfferings
              - ec2:DescribeInstanceTypes
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeSubnets
              - pricing:GetProducts
              - ec2:DeleteLaunchTemplate
              - ec2:RunInstances
              - ec2:TerminateInstances
            Resource: "*"
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: "arn:aws:ssm:*:*:parameter/aws/service/*"
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: "arn:aws:iam::*:role/KarpenterNodeRole-argocd-training"
          - Effect: Allow
            Action:
              - eks:DescribeCluster
            Resource: "arn:aws:eks:us-east-1:*:cluster/argocd-training"
          - Effect: Allow
            Action:
              - iam:CreateInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              - iam:GetInstanceProfile
              - iam:TagInstanceProfile
              - iam:ListInstanceProfiles
            Resource: "*"
          - Effect: Allow
            Action:
              - sqs:CreateQueue
              - sqs:DeleteQueue
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:TagQueue
            Resource: "*"

    # Service Account for AWS Load Balancer Controller
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

    # Service Account for External Secrets Operator (Day 1)
    - metadata:
        name: external-secrets
        namespace: external-secrets-system
      wellKnownPolicies:
        externalDNS: false
        certManager: false
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess

    # Service Accounts for ArgoCD components
    # argocd-server - Main server component
    - metadata:
        name: argocd-server
        namespace: argocd
      roleName: ArgocdServer-argocd-training
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
              - "sts:AssumeRoleWithWebIdentity"
            Resource: "*"
          - Effect: Allow
            Action:
              - "eks:DescribeCluster"
            Resource: "*"

    # argocd-application-controller - Application controller
    - metadata:
        name: argocd-application-controller
        namespace: argocd
      roleName: ArgocdApplicationController-argocd-training
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
              - "sts:AssumeRoleWithWebIdentity"
            Resource: "*"
          - Effect: Allow
            Action:
              - "eks:DescribeCluster"
            Resource: "*"

    # argocd-repo-server - Repository server
    - metadata:
        name: argocd-repo-server
        namespace: argocd
      roleName: ArgocdRepoServer-argocd-training
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:*"
            Resource: "*"

    # argocd-applicationset-controller - ApplicationSet controller
    - metadata:
        name: argocd-applicationset-controller
        namespace: argocd
      roleName: ArgocdApplicationSetController-argocd-training
      attachPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:*"
            Resource: "*"

# Managed Node Groups - Minimal for Karpenter and core components
managedNodeGroups:
  # System Node Group - For Karpenter and core cluster components only
  - name: system-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true

    # Spread across AZs
    availabilityZones:
      - us-east-1a
      - us-east-1b

    labels:
      role: system
      workload-type: core
      karpenter.sh/controller: "true"

    taints:
      - key: CriticalAddonsOnly
        value: "true"
        effect: NoSchedule

    tags:
      karpenter.sh/discovery: argocd-training
      Name: argocd-training-system-nodes

    iam:
      withAddonPolicies:
        imageBuilder: true
        externalDNS: false
        certManager: false
        appMesh: false
        ebs: true
        fsx: false
        efs: false
        albIngress: true
        cloudWatch: true

# CloudWatch Logging
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
    logRetentionInDays: 7

# Addons - Essential cluster addons
addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  - name: coredns
    version: latest

  - name: kube-proxy
    version: latest

  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true
